// AUTO-GENERATED by scripts/build-aspects.mjs — do not edit by hand.
// Re-runs on `npm run dev`, `npm run build`, and `npm run start`.

export type GeneratedAspect = {
  n: number;
  paths: { 0: string; 1?: string; 2?: string; 3?: string };
};

export const generatedAspects: GeneratedAspect[] = [
  {
    "n": 1,
    "paths": {
      "0": "/aspects/aspect-1-0.svg",
      "1": "/aspects/aspect-1-1.svg",
      "2": "/aspects/aspect-1-2.svg"
    }
  },
  {
    "n": 2,
    "paths": {
      "0": "/aspects/aspect-2-0.svg",
      "1": "/aspects/aspect-2-1.svg"
    }
  },
  {
    "n": 3,
    "paths": {
      "0": "/aspects/aspect-3-0.svg",
      "1": "/aspects/aspect-3-1.svg",
      "2": "/aspects/aspect-3-2.svg"
    }
  }
];
