#!/usr/bin/env node
/**
 * Scans public/aspects/ for files matching:
 *   aspect-<n>-<k>.<ext>      (n = aspect number, k = 0..3, ext = png/jpg/jpeg/webp/svg)
 *
 *   k = 0  → developer / current image  (required)
 *   k = 1  → AI alternative 1            (optional)
 *   k = 2  → AI alternative 2            (optional)
 *   k = 3  → AI alternative 3            (optional)
 *
 * Writes src/content/aspects.generated.ts with the discovered aspects.
 * If no files are found, writes an empty manifest.
 */
import { readdir, mkdir, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const SRC_DIR = join(ROOT, "public", "aspects");
const OUT_FILE = join(ROOT, "src", "content", "aspects.generated.ts");

const PATTERN = /^aspect-(\d+)-([0-3])\.(png|jpe?g|webp|svg)$/i;

async function main() {
  if (!existsSync(SRC_DIR)) {
    await mkdir(SRC_DIR, { recursive: true });
  }
  const entries = await readdir(SRC_DIR).catch(() => []);
  const map = new Map();
  for (const name of entries) {
    const m = name.match(PATTERN);
    if (!m) continue;
    const n = parseInt(m[1], 10);
    const k = parseInt(m[2], 10);
    if (!map.has(n)) map.set(n, {});
    map.get(n)[k] = `/aspects/${name}`;
  }

  const aspects = [...map.keys()]
    .sort((a, b) => a - b)
    .filter((n) => map.get(n)[0] != null) // require developer image
    .map((n) => ({ n, paths: map.get(n) }));

  const banner = `// AUTO-GENERATED by scripts/build-aspects.mjs — do not edit by hand.
// Re-runs on \`npm run dev\`, \`npm run build\`, and \`npm run start\`.
`;
  const body = `export type GeneratedAspect = {
  n: number;
  paths: { 0: string; 1?: string; 2?: string; 3?: string };
};

export const generatedAspects: GeneratedAspect[] = ${JSON.stringify(aspects, null, 2)};
`;

  await mkdir(dirname(OUT_FILE), { recursive: true });
  await writeFile(OUT_FILE, banner + "\n" + body);
  // eslint-disable-next-line no-console
  console.log(`[build-aspects] discovered ${aspects.length} aspect(s) → ${OUT_FILE}`);
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error("[build-aspects]", err);
  process.exit(1);
});
